config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "orienteerings#index"

  resources :users
  resources :orienteerings do
    resources :controls do
      resources :answers
    end
    member do
      get "result"
    end

  end
end

app/models/answer.rb
class Answer < ApplicationRecord

  validates :answer, presence: true

  belongs_to :user
  belongs_to :control

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/control.rb
class Control < ApplicationRecord

  validates :name, presence: true
  validates :question, presence: true
  validates :answer, presence: true
  validates :position_lat, presence: true
  validates :position_lng, presence: true
  validates :point, presence: true

  has_many :answers
  belongs_to :orienteering

end

app/models/orienteering.rb
class Orienteering < ApplicationRecord

  validates :name, presence: true
  validates :opendate_at, presence: true

  has_many :orienteering_users
  has_many :users, through: :orienteering_users
  has_many :controls
  belongs_to :host, class_name: "User"

  def calc_scores
    array_users = []
    array_user_ids = []
    users.each do |user|
      array_users << user.name
      array_user_ids << user.id
    end
    array_user_scores = Array.new(users.length, 0)

    controls.each do |control|
      control.answers.each do |answer|
        if answer.answer == control.answer
          index = array_user_ids.index(answer.user_id)
          array_user_scores[index] += control.point.to_i
        end
      end
    end
    return array_user_scores
  end

end

app/models/orienteering_user.rb
class OrienteeringUser < ApplicationRecord

  belongs_to :orienteering
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orienteering_users
  has_many :orienteerings, through: :orienteering_users
  has_many :host_orienteerings, foreign_key: "host_id", class_name: "Orienteering", dependent: :destroy
  has_many :answers

  validates :name, presence: true

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @orienteering = Orienteering.find(params[:orienteering_id])
    @control = Control.find(params[:control_id])

    unless OrienteeringUser.where(user_id: current_user.id, orienteering_id: @orienteering.id).present?
      ouser = OrienteeringUser.new(user_id: current_user.id, orienteering_id: @orienteering.id)
      ouser.save
    end

    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to orienteering_path(params[:orienteering_id]), notice: "Answer was saved."
    else
      render "controls/show"
    end
  end

  def update
    @orienteering = Orienteering.find(params[:orienteering_id])
    @control = Control.find(params[:control_id])
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to orienteering_path(params[:orienteering_id]), notice: "Answer was updated."
    else
      render "controls/show"
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer).merge(control_id: params[:control_id], user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController

  before_action :set_orienteering, only: [:new, :show, :edit, :create, :update]
  before_action :check_curernt_user, only: [:new, :edit]

  def new
    @control = @orienteering.controls.new
    control_last = @orienteering.controls.order(id: "DESC").limit(1)
    set_latlng_zoomflag(control_last[0])
  end

  def show
    @control = Control.find(params[:id])

    if Answer.where(user_id: current_user.id, control_id: @control.id).present?
      @answer = Answer.find_by(user_id: current_user.id, control_id: @control.id)
    else
      @answer = Answer.new
    end
  end

  def edit
    @control = Control.find(params[:id])
  end

  def create
    @control = @orienteering.controls.new(control_params)
    if @control.save
      redirect_to orienteering_path(@orienteering.id), notice: "Control was created."
    else
      control_last = @orienteering.controls.order(id: "DESC").limit(1)
      set_latlng_zoomflag(control_last[0])
      render :new
    end
  end

  def update
    @control = Control.find(params[:id])
    if @control.update(control_params)
      redirect_to orienteering_path(@orienteering.id), notice: "Control was updated."
    else
      render :edit
    end
  end

  private

  def control_params
    params.require(:control).permit(:name, :question, :choice, :answer, :position_lat, :position_lng, :point)
  end

  def set_orienteering
    @orienteering = Orienteering.find(params[:orienteering_id])
  end

  def check_curernt_user
    unless @orienteering.host_id == current_user.id
      redirect_to orienteering_path(@orienteering.id), notice: "You don\'t have access authority."
    end
  end

  def set_latlng_zoomflag(control_last)
    if control_last.present?
      @lat = control_last.position_lat
      @lng = control_last.position_lng
      @zoomflag = 1
    else # tokyo sta.
      @lat = 35.6812584  
      @lng = 139.7667767
      @zoomflag = 0
    end
  end

end

app/controllers/orienteerings_controller.rb
class OrienteeringsController < ApplicationController

  before_action :set_orienteering, only: [:show, :edit, :update, :result]
  before_action :check_curernt_user, only: [:edit, :result]

  def index
    @orienteerings = Orienteering.where('opendate_at <= ?', Time.current).or(Orienteering.where(host_id: current_user.id)).order(created_at: "DESC")
  end

  def show
    @controls = @orienteering.controls
    set_latlng(@controls)
  end

  def new
    @orienteering = Orienteering.new
  end

  def edit
  end

  def create
    @orienteering = Orienteering.new(orienteering_params)
    if @orienteering.save
      redirect_to root_path, notice: "Orienteering was created."
    else
      render :new
    end
  end

  def update
    if @orienteering.update(orienteering_params)
      redirect_to root_path, notice: "Orienteering was updated."
    else
      render :edit
    end
  end

  def result
    @controls = @orienteering.controls.includes(:answers)
    @users = @orienteering.users
    @array_user_scores = @orienteering.calc_scores
  end

  private

  def orienteering_params
    params.require(:orienteering).permit(:name, :opendate_at).merge(host_id: current_user.id)
  end

  def set_orienteering
    @orienteering = Orienteering.find(params[:id])
  end

  def check_curernt_user
    unless @orienteering.host_id == current_user.id
      redirect_to root_path, notice: "You don\'t have access authority."
    end
  end

  def set_latlng(controls)
    if controls.present?
      @lat = controls.first.position_lat
      @lng = controls.first.position_lng
    else # tokyo sta.
      @lat = 35.6812584  
      @lng = 139.7667767
    end

    @array_lats = []
    @array_lngs = []
    controls.each do |control|
      @array_lats << control.position_lat
      @array_lngs << control.position_lng
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/controls/_form.html.haml
- if control.errors.any?
  .control__errors.error-message-box
    %h2= "#{control.errors.full_messages.count}件のエラーが発生しました。"
    %ul
      - control.errors.full_messages.each do |message|
        %li= message
= form_with model: [orienteering, control], local: true do |f|
  .control-form__field
    = f.label :name, "Control name", class: 'control-form__label'
    = f.text_field :name, class: 'control-form__input', placeholder: 'input control name'
  .control-form__field
    = f.label :question, "Question", class: 'control-form__label'
    = f.text_area :question, class: 'control-form__input', placeholder: 'input question'
  .control-form__field
    = f.label :choice, "Choices", class: 'control-form__label'
    = f.text_area :choice, class: 'control-form__input', placeholder: 'input choices', size: "20x5"
  .control-form__field
    = f.label :answer, "Answer", class: 'control-form__label'
    = f.text_field :answer, class: 'control-form__input', placeholder: 'input answer'
  .control-form__field
    = f.label :point, "Point", class: 'control-form__label'
    = f.text_field :point, class: 'control-form__input', placeholder: 'input point'
  .control-form__field
    = f.label :position_lat, "Position_lat", class: 'control-form__label'
    = f.text_field :position_lat, class: 'control-form__input input-gray', readonly: ""
  .control-form__field
    = f.label :position_lng, "Position_lng", class: 'control-form__label'
    = f.text_field :position_lng, class: 'control-form__input input-gray', readonly: ""
  .control-form__actions
    = f.submit class: 'control-form__button'

#floating-panel
  %input{id: "address", type: "textbox"}
  %input{id: "submit", type: "button", value: "Search"}
#map

app/views/controls/edit.html.haml
= render "layouts/google_map_api"
= render "layouts/header"
= render partial: "layouts/header_orienteering", locals: { orienteering: @orienteering }
= render partial: "layouts/header_control", locals: { orienteering: @orienteering, control: @control }
.wrapper
  .control-edit-contents
    = render partial: "form", locals: { orienteering: @orienteering, control: @control }
= render "layouts/footer"

:javascript
  let lat = parseFloat('#{@control.position_lat}');
  let lng = parseFloat('#{@control.position_lng}');
  let map;
  let marker;
  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 16,
      center: { lat: lat, lng: lng }
    });
    const geocoder = new google.maps.Geocoder();
    document.getElementById("submit").addEventListener("click", () => {
      geocodeAddress(geocoder, map);
    });
    marker = new google.maps.Marker({position: map.getCenter(), map: map});

    map.addListener('center_changed', dispLatLng);
  }

  function geocodeAddress(geocoder, resultsMap) {
    resultsMap.setZoom(16);
    const address = document.getElementById("address").value;
    geocoder.geocode({ address: address }, (results, status) => {
      if (status === "OK") {
        resultsMap.setCenter(results[0].geometry.location);
        // new google.maps.Marker({
        //   map: resultsMap,
        //   position: results[0].geometry.location
        // });
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function dispLatLng(){
    let latlng = map.getCenter();
    marker.setMap(null);
    marker = new google.maps.Marker({position: latlng, map: map});

    $("#control_position_lat").val(latlng.lat());
    $("#control_position_lng").val(latlng.lng());
  }

app/views/controls/new.html.haml
= render "layouts/google_map_api"
= render "layouts/header"
= render partial: "layouts/header_orienteering", locals: { orienteering: @orienteering }
.wrapper
  .control-new-contents
    = render partial: "form", locals: { orienteering: @orienteering, control: @control }
= render "layouts/footer"

:javascript
  let lat = parseFloat('#{@lat}');
  let lng = parseFloat('#{@lng}');
  let zoomflag = parseFloat('#{@zoomflag}');
  let zoom;
  if (zoomflag == "1") {zoom = 16;} else {zoom = 12;}
  let map;
  let marker;
  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: zoom,
      center: { lat: lat, lng: lng }
    });
    const geocoder = new google.maps.Geocoder();
    document.getElementById("submit").addEventListener("click", () => {
      geocodeAddress(geocoder, map);
    });
    marker = new google.maps.Marker({position: map.getCenter(), map: map});

    map.addListener('center_changed', dispLatLng);
  }

  function geocodeAddress(geocoder, resultsMap) {
    resultsMap.setZoom(16);
    const address = document.getElementById("address").value;
    geocoder.geocode({ address: address }, (results, status) => {
      if (status === "OK") {
        resultsMap.setCenter(results[0].geometry.location);
        // new google.maps.Marker({
        //   map: resultsMap,
        //   position: results[0].geometry.location
        // });
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
  }

  function dispLatLng(){
    let latlng = map.getCenter();
    marker.setMap(null);
    marker = new google.maps.Marker({position: latlng, map: map});

    $("#control_position_lat").val(latlng.lat());
    $("#control_position_lng").val(latlng.lng());
  }

app/views/controls/show.html.haml
= render "layouts/google_map_api"
= render "layouts/header"
= render partial: "layouts/header_orienteering", locals: { orienteering: @orienteering }
= render partial: "layouts/header_control", locals: { orienteering: @orienteering, control: @control }
.wrapper
  .control-show-contents
    .control-details
      %p= "Control name:"
      %p.indent= @control.name
      %p= "Question:"
      %p.indent= @control.question
      %p= "Choices:"
      %p.indent.choice= @control.choice
      %p= "Point:"
      %p.indent= @control.point
    - if @answer.errors.any?
      .answer__errors.error-message-box
        %h2= "#{@answer.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @answer.errors.full_messages.each do |message|
            %li= message
    = form_with model: [@orienteering, @control, @answer], local: true do |f|
      .control-form__field
        = f.label :answer, "Answer", class: 'control-form__label'
        = f.text_field :answer, class: 'control-form__input', placeholder: 'input answer'
      .control-form__actions
        = f.submit "Submit", class: 'control-form__button'
    #map
    .geolocation_message
= render "layouts/footer"

:javascript
  let lat = parseFloat('#{@control.position_lat}');
  let lng = parseFloat('#{@control.position_lng}');
  let map;
  let marker;
  let infoWindow;
  let marker_current;

  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 17,
      center: { lat: lat, lng: lng }
    });
    marker = new google.maps.Marker({position: map.getCenter(), map: map});

    infoWindow = new google.maps.InfoWindow;
    // Try HTML5 geolocation.
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        let pos = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };

        marker_current = new google.maps.Marker({position: pos, map: map,
          icon: {
            path: google.maps.SymbolPath.CIRCLE,
            scale: 10
          }
        });
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
  }

  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    let message;
    if (browserHasGeolocation) {
      message = 'Error: The Geolocation service failed.';
    } else {
      message = 'Error: Your browser doesn\'t support geolocation.';
    }
    let html = buildHTML(message);
    $('.geolocation_message').append(html);

    //  infoWindow.setPosition(pos);
    //  infoWindow.setContent(browserHasGeolocation ?
    //                        'Error: The Geolocation service failed.' :
    //                        'Error: Your browser doesn\'t support geolocation.');
    //  infoWindow.open(map);
  }

  function buildHTML(message){
    let html = `<p>${message}</p>`;
    return html;
  }

app/views/layouts/_footer.html.haml
%footer.footer-after-signin
  %p<>Orienteering App for Recreation

app/views/layouts/_footer_before-signin.html.haml
%footer.footer-before-signin

app/views/layouts/_google_map_api.html.haml
%script{:defer => "", :src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAk3yZOiqYz38KM80EH9LxlDW1mrUAuCBI&callback=initMap&libraries=&v=weekly"}

app/views/layouts/_header.html.haml
%header.header-after-signin
  .header-after-signin__contents
    .left
      = link_to root_path do
        %h1= current_user.name
    .right
      = link_to edit_user_path(current_user.id), class: "a-tag__icon" do
        = icon('fas', 'cog', class: "icon-cog")

app/views/layouts/_header_before-signin.html.haml
%header.header-before-signin
  %h1<>Orienteering App for Recreation

app/views/layouts/_header_control.haml
%header.header_control
  .header_control__contents
    .left
      = link_to orienteering_control_path(orienteering.id, control.id) do
        %h1= control.name
    .right
      - if orienteering.host_id == current_user.id
        = link_to edit_orienteering_control_path(orienteering.id, control.id), class: "a-tag__icon" do
          = icon('fas', 'cog', class: "icon-cog")

app/views/layouts/_header_orienteering.html.haml
%header.header_orienteering
  .header_orienteering__contents
    .left
      = link_to orienteering_path(orienteering.id) do
        %h1= orienteering.name
    .right
      %h1= "host: #{orienteering.host.name}"
      - if orienteering.host_id == current_user.id
        = link_to edit_orienteering_path(orienteering.id), class: "a-tag__icon" do
          = icon('fas', 'cog', class: "icon-cog")

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OrienteeringApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application' #add
    %meta{ name: 'viewport', content: 'initial-scale=1.0, user-scalable=no' }
    %script{src: "https://polyfill.io/v3/polyfill.min.js?features=default"}
    = favicon_link_tag
  %body
    = render 'layouts/notifications' #add
    = yield

app/views/orienteerings/_form.html.haml
- if orienteering.errors.any?
  .orienteering__errors.error-message-box
    %h2= "#{orienteering.errors.full_messages.count}件のエラーが発生しました。"
    %ul
      - orienteering.errors.full_messages.each do |message|
        %li= message
= form_with model: orienteering, local: true do |f|
  .orienteering-form__field
    = f.label :name, "Orienteering name", class: 'orienteering-form__label'
    = f.text_field :name, class: 'orienteering-form__input', placeholder: 'input orienteering name'
  .orienteering-form__field.orienteering-form__select
    = f.label :opendate_at, "Open date", class: 'orienteering-form__label'
    = f.datetime_select :opendate_at, use_month_numbers: true, class: 'orienteering-form__input'
  .orienteering-form__actions
    = f.submit class: 'orienteering-form__button'

app/views/orienteerings/edit.html.haml
= render "layouts/header"
= render partial: "layouts/header_orienteering", locals: { orienteering: @orienteering }
.wrapper
  .orienteering-edit-contents
    = render partial: "form", locals: { orienteering: @orienteering }
= render "layouts/footer"

app/views/orienteerings/index.html.haml
= render "layouts/header"
.wrapper
  .orienteering-index-contents
    %h2<>Orienteering list
    .table-div
      .table-div__child
        %table
          %tr
            %th<>ID
            %th<>Orienteering
            %th<>Host
            %th<>Status
          - @orienteerings.each do |o|
            %tr
              %td= o.id
              %td.orienteering
                = link_to orienteering_path(o.id) do
                  %span= o.name
              %td= o.host.name
              - if o.opendate_at <= Time.current
                %td<>Open
              - else
                %td<>Close
    = link_to new_orienteering_path, class: "a-tag-button" do
      %button<>create orienteering
= render "layouts/footer"

app/views/orienteerings/new.html.haml
= render "layouts/header"
.wrapper
  .orienteering-new-contents
    = render partial: "form", locals: { orienteering: @orienteering }
= render "layouts/footer"

app/views/orienteerings/result.html.haml
= render "layouts/header"
= render partial: "layouts/header_orienteering", locals: { orienteering: @orienteering }
.wrapper
  .orienteering-result-contents
    %h2<>Results
    .table-div
      .table-div__child
        %table
          %tr
            %th<>No.
            %th<>User
            %th<>Score
          - @users.each_with_index do |user, i|
            %tr
              %td= i+1
              %td= user.name
              %td= @array_user_scores[i]
    %h2<>All answers
    .table-div
      .table-div__child
        %table
          %tr
            %th<>no.
            %th<>control
            %th<>user
            %th<>answer
            %th<>point
          - i = 0
          - @controls.each do |control|
            - control.answers.includes(:user).each do |answer| 
              %tr
                %td= i+1
                %td= control.name
                %td= answer.user.name
                %td= answer.answer
                - if answer.answer == control.answer
                  %td= control.point
                - else
                  %td= 0
                - i += 1
= render "layouts/footer"

app/views/orienteerings/show.html.haml
= render "layouts/google_map_api"
= render "layouts/header"
= render partial: "layouts/header_orienteering", locals: { orienteering: @orienteering }
.wrapper
  .orienteering-show-contents
    %h2<>Control list
    .table-div
      .table-div__child
        %table
          %tr
            %th<>No.
            %th<>Control
            %th<>Point
            %th<>Check
          - @controls.each_with_index do |control, i|
            %tr
              %td= i+1
              %td.control
                = link_to orienteering_control_path(@orienteering.id, control.id) do
                  %span= control.name
              %td= control.point
              %td
                - if control.answers.where(user_id: current_user.id).present?
                  %span<>Done
    #map
    .geolocation_message
    - if @orienteering.host_id == current_user.id
      .div-only-host
        %h2<>Host menu
        = link_to new_orienteering_control_path(@orienteering.id) do
          %button<>Create control
        = link_to result_orienteering_path(@orienteering.id) do
          %button<>Result
= render "layouts/footer"

:javascript
  let lat = parseFloat('#{@lat}');
  let lng = parseFloat('#{@lng}');

  let location_lats = JSON.parse('#{raw @array_lats}');
  let location_lngs = JSON.parse('#{raw @array_lngs}');
  let locations = [];
  let labels = [];

  for (let i=0; i<location_lats.length; i++) {
    locations.push({lat: parseFloat(location_lats[i]), lng: parseFloat(location_lngs[i])});
    labels.push(String(i+1));
  }

  let map;
  let markers;
  let infoWindow;
  let marker_current;

  function initMap() {
    map = new google.maps.Map(document.getElementById("map"), {
      zoom: 16,
      center: { lat: lat, lng: lng }
    });

    markers = locations.map(function(location, i) {
      return new google.maps.Marker({
        position: location,
        map: map, // add
        label: labels[i]
      });
    });

    infoWindow = new google.maps.InfoWindow;
    // Try HTML5 geolocation.
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function(position) {
        let pos = {
          lat: position.coords.latitude,
          lng: position.coords.longitude
        };

        marker_current = new google.maps.Marker({position: pos, map: map,
          icon: {
            path: google.maps.SymbolPath.CIRCLE,
            scale: 10
          }
        });
      }, function() {
        handleLocationError(true, infoWindow, map.getCenter());
      });
    } else {
      // Browser doesn't support Geolocation
      handleLocationError(false, infoWindow, map.getCenter());
    }
  }

  function handleLocationError(browserHasGeolocation, infoWindow, pos) {
    let message;
    if (browserHasGeolocation) {
      message = 'Error: The Geolocation service failed.';
    } else {
      message = 'Error: Your browser doesn\'t support geolocation.';
    }
    let html = buildHTML(message);
    $('.geolocation_message').append(html);

    //  infoWindow.setPosition(pos);
    //  infoWindow.setContent(browserHasGeolocation ?
    //                        'Error: The Geolocation service failed.' :
    //                        'Error: Your browser doesn\'t support geolocation.');
    //  infoWindow.open(map);
  }

  function buildHTML(message){
    let html = `<p>${message}</p>`;
    return html;
  }

app/views/users/edit.html.haml
= render "layouts/header"
.wrapper
  .users-edit-contents
    = link_to destroy_user_session_path, method: :delete do
      %button<>Sign out
    = link_to root_path do
      %button<>Back to top
= render "layouts/footer"